//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPFaq.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class faq_question
    {
        public faq_question()
        {
            this.faq_answer = new HashSet<faq_answer>();
            this.faq_attach = new HashSet<faq_attach>();
        }
    
        public int ID { get; set; }
        public string Question { get; set; }
        public string Questioner { get; set; }
        public Nullable<bool> IsSolved { get; set; }
        public string KeyWord { get; set; }
        public Nullable<int> SearchCount { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual ICollection<faq_answer> faq_answer { get; set; }
        public virtual ICollection<faq_attach> faq_attach { get; set; }
        public virtual faq_category faq_category { get; set; }
    }
}
